Repository AY2425S1-CS2103T-F14a-1/tp, pull requests merged in 2024-10, with the labels that each got.

#53 Add Subject class
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/model/person/Subjects.java
  src/test/java/seedu/address/model/person/SubjectTest.java
Labels: type.Task, priority.High

#58 Delete tag attribute and related code
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#56 Add fee class
  src/main/java/seedu/address/model/person/Fee.java
  src/main/java/seedu/address/model/person/Owed.java
  src/main/java/seedu/address/model/person/Paid.java
  src/main/java/seedu/address/model/person/Rate.java
  src/test/java/seedu/address/model/person/FeeTest.java
  src/test/java/seedu/address/model/person/OwedTest.java
  src/test/java/seedu/address/model/person/PaidTest.java
  src/test/java/seedu/address/model/person/RateTest.java
Labels: type.Task, priority.High

#54 Add Schedule class
  src/main/java/seedu/address/model/person/Days.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/test/java/seedu/address/model/person/DaysTest.java
  src/test/java/seedu/address/model/person/ScheduleTest.java
Labels: type.Task, priority.High

#64 Add support for schedule for add and edit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#74 Update PersonTest method to test Schedule
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement, type.Task, priority.High

#75 Update add and edit command with /fee
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Rate.java
  src/main/java/seedu/address/model/person/Schedule.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#80 Update phone number constraint
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Task

#84 Update Duplicate Detection to include Name and Phone
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#83 Update Add and Edit command with OwedAmount
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Owed.java
  src/main/java/seedu/address/model/person/OwedAmount.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/OwedAmountTest.java
  src/test/java/seedu/address/model/person/OwedTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#81 Update add and edit command with Paid
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Paid.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#93 Updated prefixes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Enhancement, type.Task

#97 Update name
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement, type.Task

#85 Add-IncomeCommand-Test
  src/main/java/seedu/address/logic/commands/IncomeCommand.java
  src/test/java/seedu/address/logic/commands/IncomeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#95 Update AddressBookParser
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/IncomeCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement, type.Task

#102 Add test to AppParameters
  src/test/java/seedu/address/AppParametersTest.java
Labels: type.Task, priority.Medium

#98 Update UG for v1.3 - Add and Edit command
  docs/UserGuide.md
Labels: priority.Medium

#105 Update prefix and improve gui
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Task, priority.High, severity.Medium

#109 MainApp.java: Update version
  src/main/java/seedu/address/MainApp.java
Labels: priority.High

#116 Change paid to paidAmount
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/IncomeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/PaidAmount.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/commands/IncomeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/student/PaidAmountTest.java
  src/test/java/seedu/address/model/student/PaidTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Bug, priority.High

#119 Fix Ui bug
  src/main/java/seedu/address/model/student/Student.java
  src/main/resources/view/StudentListCard.fxml
Labels: type.Bug, severity.High

#121 Add Pay Command
  docs/UserGuide.md
  docs/images/payResult.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PayCommandParser.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/PayCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/PayCommandParserTest.java
Labels: type.Task

#135 Update UG
  docs/UserGuide.md
  docs/images/addResult.jpeg
Labels: type.Task, priority.High

#129 Add settle command
  src/main/java/seedu/address/logic/commands/SettleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SettleCommandParser.java
  src/main/java/seedu/address/model/student/OwedAmount.java
  src/main/java/seedu/address/model/student/PaidAmount.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SettleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SettleCommandParserTest.java
  src/test/java/seedu/address/model/student/OwedAmountTest.java
  src/test/java/seedu/address/model/student/PaidAmountTest.java
Labels: type.Epic, priority.High

#131 Add settle command to UG
  docs/UserGuide.md
  docs/images/settleResult.png
Labels: type.Task, priority.High

#132 Add Owe Command
  docs/UserGuide.md
  docs/images/oweResult.png
  src/main/java/seedu/address/logic/commands/OweCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/OweCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/OweCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/OweCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#137 Update UG
  docs/UserGuide.md
  docs/images/UGTeach.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#139 Update UG edit command
  docs/UserGuide.md
  docs/images/editResult.png
Labels: type.Task

#141 Edit UML diagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#148 Update UML diagrams to include subject
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#146 Update model uml diagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#149 Branch update UG owed amount and tag
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task

#152 Add remind command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/RemindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Schedule.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/ScheduleTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: type.Task

#153 Remove comment out code for tag
  src/main/java/seedu/address/ui/StudentCard.java
Labels: type.Task, priority.Medium, severity.VeryLow, severity.Medium

#154 MainApp.java: Update version
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#156 Change help URL
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, type.Bug, priority.High, severity.High

#157 Update error in subject help message and Ug
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/Subject.java
Labels: type.Bug, severity.Medium

#159 Change helpMessage.png
  docs/images/helpMessage.png
Labels: type.Bug, priority.Medium, severity.Medium, severity.High

#161 Add ParserUtil#parseOwedAmount test
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Low

#160 Add tests for ParserUtil#parsePaidAmount
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Medium, severity.Low

#176 Fix box header issues and move summary table to top
  docs/UserGuide.md
Labels: type.Bug

#178 Add test cases for parseSchedule
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.Medium

#180 Update DG title and Acknowledgement
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium

#175 Add tests for parseSubject method in parser util
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Medium, severity.VeryLow

#201 Update Model PUML
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium, severity.VeryLow

#183 Update UG for Remind and Delete
  docs/UserGuide.md
  docs/images/deleteResult.png
  docs/images/remindResult.png
Labels: priority.Medium, severity.VeryLow, alpha-bug

#189 Update UG for Find
  docs/UserGuide.md
Labels: type.Bug, priority.High, alpha-bug

#207 Fix edit command links
  docs/UserGuide.md
Labels: alpha-bug

#174 Update tips in add and edit for address
  docs/UserGuide.md
Labels: type.Task

#215 Update schedule message constraint
  src/main/java/seedu/address/model/student/Schedule.java
Labels: alpha-bug

#181 Update reason for duplicates checking
  docs/UserGuide.md
Labels: type.Task, type.Bug, alpha-bug

#185 Format standards for Add and Edit
  docs/UserGuide.md
Labels: type.Task, type.Bug, priority.High, alpha-bug

#214 Update Fee and subclasses constraints
  src/main/java/seedu/address/model/student/Fee.java
  src/main/java/seedu/address/model/student/OwedAmount.java
  src/main/java/seedu/address/model/student/PaidAmount.java
  src/main/java/seedu/address/model/student/Rate.java
  src/test/java/seedu/address/model/student/OwedAmountTest.java
  src/test/java/seedu/address/model/student/PaidAmountTest.java
  src/test/java/seedu/address/model/student/RateTest.java
Labels: alpha-bug

#191 Add usecase for find in dg
  docs/DeveloperGuide.md
  docs/package-lock.json
Labels: type.Bug, priority.High

#221 Fix command summary link
  docs/_markbind/layouts/default.md
Labels: alpha-bug

#217 Remove count clash methods
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: severity.VeryLow

#193 Add use case for Pay
  docs/DeveloperGuide.md
Labels: type.Task, severity.VeryLow, alpha-bug

#205 Update logic UML diagram for add
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram-Logic.puml
  docs/diagrams/ParseArgsToGetStudentFieldReferenceFrame.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoSequenceDiagram-Logic.puml
Labels: type.Task, priority.High

#250 Update home tab of documentation
  docs/index.md
Labels: severity.Low, alpha-bug

#251 Update UI Screenshot
  docs/UserGuide.md
  docs/images/Ui.png
Labels: severity.VeryLow, alpha-bug

#247 Fix message usage add command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: alpha-bug

#256 Fix UG link error
  docs/UserGuide.md
Labels: alpha-bug

#240 Refactor income command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/IncomeCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/OwedAmount.java
  src/main/java/seedu/address/model/student/PaidAmount.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/IncomeCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: type.Task, priority.Medium, severity.Low, alpha-bug

#195 Update manual testing in dg for find
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#200 Update DG appendix
  docs/DeveloperGuide.md
Labels: type.Task, alpha-bug
