Repository AY2425S1-CS2103T-F14a-1/tp, pull requests merged in 2024-11, with the labels that each got.

#208 Fix formating of settle command in UG
  docs/UserGuide.md
  docs/images/settleResult.jpg
  docs/images/settleResult.png
Labels: alpha-bug

#203 Add implementation details for Owe
  docs/DeveloperGuide.md
  docs/diagrams/PaymentTrackingActivityDiagram.puml
Labels: type.Task

#209 Draw add command Activity Diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddCommandActivityDiagram.puml
Labels: type.Task, priority.High

#262 Fix bug in DG
  docs/DeveloperGuide.md
Labels: severity.VeryLow, alpha-bug

#199 Update UG for pay and owe command
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.Low

#261 Tailor NFR
  docs/DeveloperGuide.md
Labels: type.Task

#238 Fix owe command overflow
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/OweCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/OwedAmount.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/OweCommandTest.java
  src/test/java/seedu/address/logic/commands/PayCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/student/OwedAmountTest.java
Labels: severity.High, alpha-bug

#233 Update find command to perform and search
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: alpha-bug

#254 Update UG for find command AND search
  docs/UserGuide.md
  docs/images/findResult.png
Labels: alpha-bug

#236 Fix alpha bug for Pay command
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/test/java/seedu/address/logic/commands/PayCommandTest.java
  src/test/java/seedu/address/model/student/PaidAmountTest.java
Labels: severity.Medium, alpha-bug

#259 Sequence diagram for model portion of owe command
  docs/DeveloperGuide.md
  docs/diagrams/OweSequenceDigram-Model.puml
Labels: alpha-bug

#220 Add use case for settle
  docs/DeveloperGuide.md
Labels: type.Task

#245 Update UG
  docs/UserGuide.md
  docs/images/incomeResult.png
Labels: alpha-bug

#269 Fix Editing the data file errors
  docs/UserGuide.md
Labels: alpha-bug

#275 Add sequence diagram to user guide
  docs/DeveloperGuide.md
  docs/diagrams/OweSequenceDiagram-Model.puml
Labels: alpha-bug

#267 Fix handling settle
  src/main/java/seedu/address/logic/commands/SettleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SettleCommandParser.java
  src/main/java/seedu/address/model/student/OwedAmount.java
  src/main/java/seedu/address/model/student/PaidAmount.java
  src/main/java/seedu/address/model/student/SettleAmount.java
  src/test/java/seedu/address/logic/commands/SettleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SettleCommandParserTest.java
  src/test/java/seedu/address/model/student/OwedAmountTest.java
  src/test/java/seedu/address/model/student/PaidAmountTest.java
  src/test/java/seedu/address/model/student/SettleAmountTest.java
Labels: alpha-bug

#283 Add page breaks and correct format errors
  docs/UserGuide.md
Labels: alpha-bug

#282 Update use cases
  docs/DeveloperGuide.md
Labels: severity.VeryLow, alpha-bug

#277 Update Owe implementation
  docs/DeveloperGuide.md
Labels: severity.Low, alpha-bug

#295 Fix missing units bug
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/student/Rate.java
  src/main/java/seedu/address/model/student/SettleAmount.java
Labels: severity.VeryLow, alpha-bug

#274 Refine storage package
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: severity.VeryLow, alpha-bug

#284 Fix edit links in pay and owe
  docs/UserGuide.md
Labels: alpha-bug

#278 Update Model package
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/OwedAmount.java
  src/main/java/seedu/address/model/student/PaidAmount.java
  src/main/java/seedu/address/model/student/Rate.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/student/AddressTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/model/student/predicates/AttributeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/predicates/ScheduleContainsKeywordsPredicateTest.java
Labels: type.Task

#272 Change user visible ab3 instances to ugteach
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task, severity.VeryLow

#293 Update UG based on Ms Dara's comments
  docs/UserGuide.md
  docs/images/clashingSchedule.png
Labels: severity.VeryLow, alpha-bug

#300 Change screenshots
  docs/UserGuide.md
  docs/images/findResult.png
  docs/images/incomeResult.png
  docs/images/remindResult.png
  docs/images/settleResult.jpg
  docs/images/settleResult.png
Labels: severity.VeryLow, alpha-bug

#280 Update documents
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
Labels: type.Task, type.Bug, severity.Medium

#290 Make Prefixes case-insensitive
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/PayCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/OweCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SettleCommandParserTest.java
Labels: type.Task

#304 Change message for duplicates
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.Medium

#291 DG: Manual testing for pay, owe and settle command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium, alpha-bug

#287 Add manual testing add edit commands
  docs/DeveloperGuide.md
Labels: alpha-bug

#302 Fix UG for clarification on pay, owe and settle
  docs/UserGuide.md
  docs/images/listResult.png
Labels: severity.VeryLow, alpha-bug

#311 Format ug
  docs/UserGuide.md
Labels: alpha-bug

#312 Fix settle link in edit
  docs/UserGuide.md
Labels: alpha-bug

#387 Fix Doc: Update Ui.png
  docs/images/Ui.png
Labels: action.Fix

#384 Change instances of system to UGTeach
  docs/DeveloperGuide.md
Labels: action.Fix

#388 Update DG storage link
  docs/DeveloperGuide.md
Labels: action.Fix

#390 Update DG Model link
  docs/DeveloperGuide.md
Labels: action.Fix

#391 Update DG for Logic link
  docs/DeveloperGuide.md
Labels: action.Fix

#385 Fix rate and paid in success message
  src/main/java/seedu/address/logic/Messages.java
Labels: action.Fix

#393 Update DG to fix UI link
  docs/DeveloperGuide.md
Labels: action.Fix

#394 Update DG Model diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: action.Fix

#396 Update UG
  docs/UserGuide.md
Labels: action.Fix

#392 Remove extra word in ug
  docs/UserGuide.md
Labels: action.Fix

#389 Fix bug: Valid phone number rejected
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/Phone.java
  src/test/java/seedu/address/model/student/PhoneTest.java
Labels: action.Fix

#405 Ug fixes
  docs/UserGuide.md
Labels: action.Fix

#386 Make Add Command activity diagram higher level
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/UserAddCommandActivityDiagram.puml
Labels: action.Fix

#409 Add glossary for ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: action.Fix

#399 Add plan enhancements
  docs/DeveloperGuide.md
Labels: action.PlannedEnhancements

#408 Add details in quickstart
  docs/UserGuide.md
Labels: action.Fix

#395 Update UG for constraints of name
  docs/UserGuide.md
Labels: action.Fix

#404 Clarify constraints and examples in ug
  docs/UserGuide.md
  docs/images/findResult.png
Labels: action.Fix

#402 Add jar and json into glossary
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: action.Fix

#411 Fix bug where settling 499.99 from 500.00 had no response
  src/main/java/seedu/address/model/student/OwedAmount.java
  src/main/java/seedu/address/model/student/PaidAmount.java
  src/test/java/seedu/address/model/student/OwedAmountTest.java
Labels: response.Accepted, action.Fix

#415 Fix unhelpful visuals
  docs/UserGuide.md
  docs/images/addAfter.png
  docs/images/addBefore.png
  docs/images/addResult.jpeg
  docs/images/clashingSchedule.png
  docs/images/editAfter.png
  docs/images/editBefore.png
  docs/images/editResult.png
  docs/images/findResult.png
  docs/images/helpMessage.png
  docs/images/oweAfter.png
  docs/images/oweBefore.png
  docs/images/oweResult.png
  docs/images/payAfter.png
  docs/images/payBefore.png
  docs/images/payResult.png
  docs/images/settleAfter.png
  docs/images/settleBefore.png
  docs/images/settleResult.png
Labels: action.Fix

#406 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/backupData.png
Labels: action.Fix, action.PlannedEnhancements, action.KnownIssues

#398 Improve Duplicate Detection
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: action.Fix, action.PlannedEnhancements

#403 Clarify pay settle commands
  docs/UserGuide.md
Labels: action.Fix

#400 Update command summary of UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/OweCommand.java
  src/main/java/seedu/address/logic/commands/PayCommand.java
Labels: action.Fix

#414 Add known issues in ug
  docs/UserGuide.md
Labels: type.Enhancement, type.Task

#407 Add pay settle planned enhancements
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/student/Student.java
Labels: action.PlannedEnhancements

#412 Update UG
  docs/UserGuide.md
Labels: action.Fix

#417 Add crediting of work
  docs/UserGuide.md
Labels: type.Task

#419 UG Update with Known Issues
  docs/UserGuide.md
Labels: action.Fix

#420 Fix colon not bolded in UG
  docs/UserGuide.md
Labels: action.Fix
